Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.100.4"
  config.vm.define "minion2"
  
  # Shared folder with the host
  config.vm.synced_folder "./salt-shared/", "/srv/salt"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
    v.name = "minion2"
  end
  
  # Install salt-master (referred to as provisioning)
  config.vm.provision :salt do |salt|
    salt.install_type = "stable"
    salt.minion_config = "master-config/minion"
    salt.verbose = true
    salt.colorize = true
    salt.bootstrap_options = "-P -c /tmp"
  end

  
end
