Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "172.30.1.2"
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
    end
end