Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.100.2"
  config.vm.define "master"
  
  # Shared folder with the host
  config.vm.synced_folder "./salt-shared/", "/srv/salt"
  config.vm.synced_folder "../../config/master/", "/srv/pillar" # The saltstates are placed here

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
    v.name = "master"
  end
  
  # Install salt-master (referred to as provisioning)
  config.vm.provision :salt do |salt|
    salt.install_type = "stable"
    salt.install_master = true
    salt.no_minion = true
    salt.verbose = true
    salt.colorize = true
    salt.bootstrap_options = "-P -c /tmp"
  end

  
end